export const adminStyles = {
  page: { minHeight: '100vh', background: '#0b0b0b', color: '#eaeaea', fontFamily: 'Montserrat, sans-serif' },
  inner: { maxWidth: '1180px', margin: '0 auto', padding: '32px 24px 60px' },
  topbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '18px 24px',
    borderBottom: '1px solid rgba(197, 160, 89, 0.22)',
    background: 'linear-gradient(180deg, #151210, #0f0d0b)',
  },
  topbarBrand: { fontFamily: 'Playfair Display, serif', color: '#c5a059', fontSize: '1rem', letterSpacing: '0.04em' },
  topbarActions: { display: 'flex', alignItems: 'center', gap: '12px' },
  linkButton: {
    fontSize: '0.72rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#c5a059',
    background: 'transparent',
    border: '1px solid rgba(197, 160, 89, 0.4)',
    borderRadius: '999px',
    padding: '8px 16px',
    cursor: 'pointer',
    textDecoration: 'none',
  },
  headerRow: { display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px', marginBottom: '24px' },
  title: { fontFamily: 'Playfair Display, serif', color: '#c5a059', margin: 0 },
  revenueTile: {
    background: 'rgba(197, 160, 89, 0.08)',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '10px',
    padding: '12px 20px',
    textAlign: 'right',
    minWidth: '220px',
  },
  revenueLabel: { fontSize: '0.68rem', letterSpacing: '0.08em', textTransform: 'uppercase', color: '#948a76' },
  revenueValue: { fontFamily: 'Playfair Display, serif', color: '#c5a059', fontSize: '1.4rem', marginTop: '2px' },
  banner: {
    background: 'rgba(197, 160, 89, 0.1)',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '10px',
    padding: '14px 18px',
    marginBottom: '20px',
    color: '#dccfab',
    fontSize: '0.9rem',
  },
  statusCounts: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '20px' },
  statusPill: {
    fontSize: '0.72rem',
    padding: '6px 12px',
    borderRadius: '999px',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    color: '#dccfab',
    background: 'rgba(255,255,255,0.03)',
  },
  filterBar: { display: 'flex', flexWrap: 'wrap', gap: '12px', marginBottom: '20px' },
  input: {
    background: '#101010',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '6px',
    padding: '9px 12px',
    color: '#eaeaea',
    fontSize: '0.85rem',
  },
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    background: '#101010',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '6px',
    padding: '10px 12px',
    color: '#eaeaea',
    fontSize: '0.88rem',
    fontFamily: 'inherit',
    resize: 'vertical',
  },
  select: {
    background: '#101010',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '6px',
    padding: '9px 12px',
    color: '#eaeaea',
    fontSize: '0.85rem',
  },
  tableWrap: { overflowX: 'auto', border: '1px solid rgba(197, 160, 89, 0.2)', borderRadius: '10px' },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '0.85rem' },
  th: {
    textAlign: 'left',
    padding: '12px 16px',
    fontSize: '0.68rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#948a76',
    borderBottom: '1px solid rgba(197, 160, 89, 0.22)',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  td: { padding: '12px 16px', borderBottom: '1px solid rgba(255,255,255,0.06)', color: '#dccfab' },
  row: { cursor: 'pointer' },
  empty: { padding: '24px', textAlign: 'center', color: '#948a76' },
  statusBadge: {
    display: 'inline-block',
    padding: '4px 10px',
    borderRadius: '999px',
    border: '1px solid rgba(197, 160, 89, 0.4)',
    color: '#c5a059',
    fontSize: '0.75rem',
    whiteSpace: 'nowrap',
  },
  staleBadge: {
    display: 'inline-block',
    marginLeft: '8px',
    color: '#d99a52',
    fontSize: '0.78rem',
    whiteSpace: 'nowrap',
  },
  card: {
    background: '#101010',
    border: '1px solid rgba(197, 160, 89, 0.2)',
    borderRadius: '10px',
    padding: '24px',
    marginBottom: '20px',
  },
  sectionTitle: { fontFamily: 'Playfair Display, serif', color: '#c5a059', fontSize: '1.05rem', margin: '0 0 14px' },
  backLink: { color: '#c5a059', fontSize: '0.85rem', textDecoration: 'none', display: 'inline-block', marginBottom: '20px' },
  itemRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '14px 0',
    borderBottom: '1px solid rgba(255,255,255,0.06)',
    cursor: 'pointer',
  },
  overlay: {
    position: 'fixed',
    inset: 0,
    zIndex: 300,
    background: 'rgba(0,0,0,0.6)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '24px',
  },
  panel: {
    width: '100%',
    maxWidth: '480px',
    maxHeight: '80vh',
    overflowY: 'auto',
    background: '#17140f',
    border: '1px solid rgba(197, 160, 89, 0.3)',
    borderRadius: '12px',
    padding: '28px',
  },
  primaryButton: {
    fontSize: '0.72rem',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    color: '#000',
    background: '#d4af37',
    border: 'none',
    borderRadius: '999px',
    padding: '10px 20px',
    cursor: 'pointer',
    fontWeight: 600,
  },
};
