// src/styles/coffretCadeauConfiguratorStyles.js
//
// Copie volontaire de la mise en page du configurateur vin, pour le coffret
// cadeau neutre (src/pages/ConfiguratorPage.jsx). Dupliquée plutôt
// qu'importée pour ne jamais toucher au fichier vin, qui doit rester
// strictement inchangé.
import { HEADER_HEIGHT } from '../components/Header';

export const coffretCadeauConfiguratorStyles = {
  pageContainer: {
    display: 'flex',
    justifyContent: 'center',
    height: `calc(100vh - ${HEADER_HEIGHT}px)`,
    width: '100%',
    background: 'linear-gradient(135deg, #050505 0%, #111 45%, #0d0d0d 100%)',
    color: '#f6f1e8',
    fontFamily: '"Optima", "Didot", "Helvetica Neue", sans-serif',
    overflow: 'hidden',
    boxSizing: 'border-box',
  },
  leftPanel: {
    width: 'min(60%, 900px)',
    minWidth: '320px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    padding: '24px 28px 28px',
    overflowY: 'auto',
    background: 'linear-gradient(145deg, #0f0f0f 0%, #161616 100%)',
    borderRight: '1px solid rgba(212, 175, 55, 0.16)',
  },
  rightPanel3D: {
    width: 'min(40%, 600px)',
    minWidth: '320px',
    boxSizing: 'border-box',
    background: 'radial-gradient(circle at top, #2d2418 0%, #030303 60%, #000 100%)',
    borderLeft: '1px solid rgba(212, 175, 55, 0.18)',
    position: 'relative',
    overflow: 'hidden',
  },
  configContainer: {
    width: '100%',
    maxWidth: '760px',
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  title: {
    fontFamily: '"Didot", "Times New Roman", serif',
    fontSize: '2rem',
    fontWeight: 'normal',
    letterSpacing: '2px',
    color: '#d4af37',
    marginBottom: '24px',
    borderBottom: '1px solid rgba(212, 175, 55, 0.2)',
    paddingBottom: '14px',
  },
  sectionCard: {
    background: 'rgba(255, 255, 255, 0.03)',
    border: '1px solid rgba(255, 255, 255, 0.08)',
    borderRadius: '16px',
    padding: '18px',
    marginBottom: '16px',
    boxShadow: '0 10px 30px rgba(0, 0, 0, 0.18)',
  },
  sectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '14px',
  },
  sectionEyebrow: {
    color: '#d4af37',
    fontSize: '0.68rem',
    letterSpacing: '2px',
    textTransform: 'uppercase',
    marginBottom: '4px',
  },
  sectionTitle: {
    fontSize: '1rem',
    color: '#f7efe3',
    margin: 0,
    fontWeight: 600,
  },
  sectionBadge: {
    color: '#c7a75b',
    fontSize: '0.72rem',
    border: '1px solid rgba(212, 175, 55, 0.25)',
    borderRadius: '999px',
    padding: '4px 10px',
  },
  sectionGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    columnGap: '16px',
    rowGap: '14px',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontSize: '0.68rem',
    textTransform: 'uppercase',
    letterSpacing: '2px',
    color: '#b6ab95',
    marginBottom: '2px',
  },
  minimalSelect: {
    width: '100%',
    backgroundColor: '#121212',
    color: '#f8f1e2',
    border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '0.95rem',
    outline: 'none',
    cursor: 'pointer',
    appearance: 'none',
    boxSizing: 'border-box',
  },
  minimalInput: {
    width: '100%',
    backgroundColor: '#121212',
    color: '#f8f1e2',
    border: '1px solid rgba(255,255,255,0.12)',
    borderRadius: '10px',
    padding: '10px 12px',
    fontSize: '0.95rem',
    outline: 'none',
    boxSizing: 'border-box',
  },
  inlineInputs: { display: 'flex', gap: '10px', marginTop: '8px' },
  colorPicker: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    height: '25px',
    width: '25px',
    padding: 0,
  },
  engravingCard: {
    gridColumn: '1 / -1',
    background: 'rgba(212, 175, 55, 0.08)',
    border: '1px solid rgba(212, 175, 55, 0.18)',
    borderRadius: '12px',
    padding: '14px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  summaryCard: {
    background: 'rgba(212, 175, 55, 0.08)',
    border: '1px solid rgba(212, 175, 55, 0.2)',
    borderRadius: '16px',
    padding: '16px 18px',
    marginBottom: '16px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '16px',
    flexWrap: 'wrap',
  },
  summaryLabel: {
    color: '#b6ab95',
    fontSize: '0.7rem',
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  summaryValue: {
    color: '#f7efe3',
    fontSize: '1rem',
    marginTop: '4px',
    fontWeight: 600,
  },
  footer: {
    marginTop: '8px',
    paddingTop: '18px',
    borderTop: '1px solid rgba(255,255,255,0.08)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '12px',
  },
  orderButton: {
    backgroundColor: '#d4af37',
    color: '#000',
    border: 'none',
    padding: '14px 34px',
    fontSize: '0.8rem',
    textTransform: 'uppercase',
    letterSpacing: '2px',
    cursor: 'pointer',
    fontWeight: 'bold',
    borderRadius: '999px',
  },
  secondaryButton: {
    backgroundColor: 'transparent',
    color: '#d4af37',
    border: '1px solid rgba(212, 175, 55, 0.5)',
    padding: '14px 28px',
    fontSize: '0.8rem',
    textTransform: 'uppercase',
    letterSpacing: '2px',
    cursor: 'pointer',
    fontWeight: 'bold',
    borderRadius: '999px',
  },
  openButton: {
    position: 'absolute',
    top: '20px',
    right: '20px',
    zIndex: 10,
    padding: '10px 20px',
    backgroundColor: 'rgba(10, 10, 10, 0.82)',
    color: '#d4af37',
    border: '1px solid rgba(212, 175, 55, 0.4)',
    cursor: 'pointer',
    textTransform: 'uppercase',
    fontSize: '0.7rem',
    letterSpacing: '1px',
    borderRadius: '999px',
  },
  viewSizeGroup: {
    position: 'absolute',
    top: '20px',
    left: '20px',
    zIndex: 10,
    display: 'flex',
    gap: '8px',
  },
  viewSizeButton: {
    padding: '10px 16px',
    borderRadius: '999px',
    backgroundColor: 'rgba(10, 10, 10, 0.82)',
    border: '1px solid rgba(255, 255, 255, 0.15)',
    color: '#f7efe3',
    cursor: 'pointer',
    textTransform: 'capitalize',
    fontSize: '0.7rem',
    letterSpacing: '1px',
  },
  viewSizeButtonActive: {
    border: '1px solid #d4af37',
    background: 'rgba(212, 175, 55, 0.16)',
    color: '#d4af37',
  },
};
